version: "3.1"
services:
    www:
        build:
            context: .
            dockerfile: ./docker/dockerfiles/www
        image: php:7.4-apache
        container_name: h11.www
        ports:
            - "8661:80"
        volumes:
            - ./src:/var/www/src/
            - ./www:/var/www/html/
            - ./vendor:/var/www/vendor/
        networks:
            - backend
    mq:
        image: rabbitmq:3-management-alpine
        container_name: h11.mq
        ports:
            - "8662:5672"
            - "8663:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PW}
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        networks:
            - backend
    sql:
        image: mysql:8
        container_name: h11.sql
        ports:
            - "8664:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PW}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
        volumes:
            - ./assets/mysql:/docker-entrypoint-initdb.d
            - ./.docker/mysql/conf:/etc/mysql/conf.d
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: h11.sqladmin
        ports:
            - "8665:80"
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PW}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
        volumes:
            - ./assets/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        networks:
            - backend
    vscode:
        image: linuxserver/code-server
        container_name: h11.vscode
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=Europe/London
            - PASSWORD=${VSCODE_PW} #optional
            - SUDO_PASSWORD=${VSCODE_ROOT_PW} #optional
            - PROXY_DOMAIN=vscode.localhost #optional
        volumes:
            - ~/.ssh:/config/.ssh
            - ./.docker/vscode/:/config
            - ./:/config/workspace
            - ~/.bashrc:/root/.bashrc
            - ~/.bashrc:/config/.bashrc
            - ~/.bash_profile:/root/.bash_profile
            - ~/.bash_profile:/config/.bash_profile
            - ~/.git-completion.bash:/root/.git-completion.bash
            - ~/.git-completion.bash:/config/.git-completion.bash
        ports:
            - "8666:8443"
        links:
            - www
        networks:
            - backend
volumes:
    persistent:
networks:
    backend:
        driver: "bridge"

